### ISSUE TITLE
this issue for a code reviewer 

### ISSUE THREAD

**Issue by ReAliens** [ReAliens/space-hub-traveller#25]
**Please check our Kanban board** 
our project link: https://github.com/ReAliens/space-hub-traveller/projects

we're gone create the space hub traveler app 
@ReAliens 
@RayhanTabase 
we are two developers working on this project

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this task! 👏 👏 
There are however a few issues that you still need to work on to go to the next task/ project but you are almost there! 🚦  🚦  


## Required Changes ♻️
- [ ] Kindly ensure that for a team with 2 people the number of cards in Backlog should be equal to 17.


<br>
Cheers!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ReAliens** [comment]
kindly check the number of cards again we already have 16 tasks in To do and 1 task in done column

**Comment by Lameck1** [comment]
Hi, @ReAliens & @RayhanTabase,

Setting up your Kanban board is complete!  It's time to go ahead and start building your project.
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
